### ISSUE TITLE
Add a username and password to Blazegraph container

### ISSUE THREAD

**Issue by gpeb2** [cambridge-cares/TheWorldAvatar#510]
Currently the Blazegraph container required no authentication.

**Comment by markushofmeister** [comment]
This should definitely result in an updated version number, as this seems to break tests when started from Windows (see the `warning` here https://github.com/cambridge-cares/TheWorldAvatar/tree/main/Agents/DerivationAgentPythonExample#test). Dockerised tests work fine within WSL, but copying credential files seems to cause permission issues when started from Windows.

So, just to keep in mind increasing version number (as you always do anyway). Just here for reference.

**Comment by sm453** [comment]
Please clarify what is meant by "the container". I believe this is about password-protecting certain URLs of the Tomcat webapp. Please also clarify which ones (all, just the web front-end, or also including the SPARQL endpoints), as this has the potential to break a lot of existing codes.

**Comment by jb2197** [comment]
> Please clarify what is meant by "the container". I believe this is about password-protecting certain URLs of the Tomcat webapp. Please also clarify which ones (all, just the web front-end, or also including the SPARQL endpoints), as this has the potential to break a lot of existing codes.

I have tried to pull the image `docker.cmclinnovations.com/blazegraph:1.1.0-510-SNAPSHOT` and can confirm that both web front-end and the SPARQL endpoint are protected. One can set up username and password when initialising RemoteStoreClient, and then the SPARQL operations via code will work fine. Otherwise, one will run into `401 Unauthorized` error. I tested with `PySparqlClient` from `pyderivationagent==1.4.1`, so I suppose anything that uses RemoteStoreClient of the latest jps-base-lib should work.
