### ISSUE TITLE
Place customisable files in a folder

### ISSUE THREAD

**Issue by kokfoongcmcl** [cambridge-cares/TheWorldAvatar#538]
It will be desirable to have all the custom files (e.g. data.json, icons) in a folder so that it's not necessary to build a new image for each variation.

This way all I have to do is to have a volume with the files in it

**Comment by mdhillman** [comment]
The DTVF now produces an empty base image that can be used by individual visualisations. This base image just needs a volume (containing the files to be hosted) to be mounted at `/var/www/html`. How this is achieved is down to the visualisation developer, although the two example visualisations do show an example of this.

If desired, the volume can be added as bind mount so that files can be moved around on the host machine for easy testing during development.
