### ISSUE TITLE
Ensure consistent building IRI

### ISSUE THREAD

**Issue by kok-foong** [cambridge-cares/TheWorldAvatar#958]
IRIs created in mapbox_footprint.sql should match IRIs in the ontop mappings. I personally prefer using full IRIs from a column rather than constructing it in the mappings to reduce potential mistakes.

**Comment by sm453** [comment]
> using full IRIs from a column rather than constructing it in the mappings to reduce potential mistakes.

I believe the reason we're not keen on that is performance. Using a string column to find things is much less efficient...

**Comment by ChungTingLao** [comment]
My preliminary test result shows that switching to full string IRIs can increase query time by 4 to 5 fold (5 seconds to 20-25 seconds). Depending on the application, this may or may not be acceptable.

An alternative solution could be that we construct IRIs by prefix + a fixed ID in integer instead of prefix + a UUID string (current approach). The tested query would take around 10 seconds to finish.
